<div class="row g-3">
<div class="col-md-4"><label class="form-label">Mã đơn</label><input type="text" name="order_code" class="form-control" value="{{ old('order_code', $order->order_code ?? '') }}"></div>
<div class="col-md-4"><label class="form-label">Khách hàng</label><input type="text" name="customer_name" class="form-control" value="{{ old('customer_name', $order->customer_name ?? '') }}"></div>
<div class="col-md-4"><label class="form-label">SĐT</label><input type="text" name="customer_phone" class="form-control" value="{{ old('customer_phone', $order->customer_phone ?? '') }}"></div>
<div class="col-md-4"><label class="form-label">Người dùng</label><select name="user_id" class="form-select"><option value="">--</option>@foreach($users as $u)<option value="{{ $u->id }}" {{ (string) old('user_id', $order->user_id ?? '') === (string) $u->id ? 'selected' : '' }}>{{ $u->full_name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Cửa hàng</label><select name="store_id" class="form-select"><option value="">--</option>@foreach($stores as $s)<option value="{{ $s->id }}" {{ (string) old('store_id', $order->store_id ?? '') === (string) $s->id ? 'selected' : '' }}>{{ $s->name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Hình thức nhận</label><input type="text" name="delivery_type" class="form-control" value="{{ old('delivery_type', $order->delivery_type ?? 'delivery') }}"></div>
<div class="col-md-4"><label class="form-label">Phương thức thanh toán</label><input type="text" name="payment_method" class="form-control" value="{{ old('payment_method', $order->payment_method ?? 'cod') }}"></div>
<div class="col-md-4"><label class="form-label">Trạng thái đơn</label><select name="order_status" class="form-select">@php($currentStatus = old('order_status', $order->order_status ?? 'pending_verification'))<option value="pending_verification" {{ $currentStatus === 'pending_verification' ? 'selected' : '' }}>Chờ xác minh</option><option value="verified" {{ $currentStatus === 'verified' ? 'selected' : '' }}>Đã xác minh</option><option value="processing" {{ $currentStatus === 'processing' ? 'selected' : '' }}>Đang xử lý</option><option value="shipping" {{ $currentStatus === 'shipping' ? 'selected' : '' }}>Đang giao</option><option value="completed" {{ $currentStatus === 'completed' ? 'selected' : '' }}>Hoàn tất</option><option value="cancelled" {{ $currentStatus === 'cancelled' ? 'selected' : '' }}>Đã hủy</option><option value="pending" {{ $currentStatus === 'pending' ? 'selected' : '' }}>Chờ xử lý cũ</option></select></div>
<div class="col-md-4"><label class="form-label">Giờ xác minh</label><input type="datetime-local" name="verified_at" class="form-control" value="{{ old('verified_at', isset($order) && $order->verified_at ? $order->verified_at->format('Y-m-d\\TH:i') : '') }}"></div>
<div class="col-md-4"><label class="form-label">Trạng thái thanh toán</label><input type="text" name="payment_status" class="form-control" value="{{ old('payment_status', $order->payment_status ?? 'unpaid') }}"></div>
<div class="col-md-4"><label class="form-label">Tạm tính</label><input type="number" step="0.01" name="subtotal" class="form-control" value="{{ old('subtotal', $order->subtotal ?? 0) }}"></div>
<div class="col-md-4"><label class="form-label">Giảm giá</label><input type="number" step="0.01" name="discount_amount" class="form-control" value="{{ old('discount_amount', $order->discount_amount ?? 0) }}"></div>
<div class="col-md-4"><label class="form-label">Phí vận chuyển</label><input type="number" step="0.01" name="shipping_fee" class="form-control" value="{{ old('shipping_fee', $order->shipping_fee ?? 0) }}"></div>
<div class="col-md-4"><label class="form-label">Tổng tiền</label><input type="number" step="0.01" name="total_amount" class="form-control" value="{{ old('total_amount', $order->total_amount ?? 0) }}"></div>
<div class="col-md-12"><label class="form-label">Địa chỉ giao</label><input type="text" name="shipping_address_text" class="form-control" value="{{ old('shipping_address_text', $order->shipping_address_text ?? '') }}"></div>
<div class="col-md-12"><label class="form-label">Ghi chú</label><textarea name="note" class="form-control" rows="2">{{ old('note', $order->note ?? '') }}</textarea></div>
</div><div class="mt-3 d-flex gap-2"><button type="submit" class="btn btn-primary">{{ isset($order) ? 'Cập nhật' : 'Tạo mới' }}</button><a href="{{ route('backend.orders') }}" class="btn btn-secondary">Quay lại</a></div>
